### ISSUE TITLE
Image sent isn't working

### ISSUE THREAD

**Issue by MohammadAmr20** [TeleGrammy/backend#103]
![image](https://github.com/user-attachments/assets/73350488-1ef7-4b36-a2bb-ee995840c592)
![image](https://github.com/user-attachments/assets/1af4f5ea-9d9e-4e6f-ba96-ec1382a23677)

There is image src and not working

**Comment by ali-bahr** [comment]
we will expand the expiry time and inform u.

**Comment by ali-bahr** [comment]
I have fixed the expiry time so the URL will probably be expired.
