### ISSUE TITLE
fetch chat

### ISSUE THREAD

**Issue by Mo-Khater** [TeleGrammy/backend#109]
populate the replied replyon in the message 
{
                "_id": "6752eff6d30f958d8ba1cb6a",
                "senderId": {
                    "_id": "672129ae7ff26e8fc7990d5e",
                    "username": "mohamed232"
                },
                "messageType": "text",
                "replyOn": null,
                "isForwarded": false,
                "isEdited": false,
                "mentions": [],
                "status": "sent",
                "content": "gg",
                "mediaUrl": "",
                "mediaKey": "",
                "timestamp": "2024-12-06T12:37:10.036Z"
            }

**Comment by ali-bahr** [comment]
there is a specific end point to get a message by it is id 
so u can use it as the user should when clicking on the reply on message should be forwarded to the this message in the chat so u gonna need the entire message

**Comment by Abdulrahman-Mostafa10** [comment]
@Mo-Khater Has it worked?
