### ISSUE TITLE
Errors in registration in profile-management.

### ISSUE THREAD

**Issue by mohamedselbohy** [TeleGrammy/backend#49]
After registration it always says User not found

![image](https://github.com/user-attachments/assets/96080c96-4ac9-4877-a7c4-541193d88cac)

![image](https://github.com/user-attachments/assets/698e8b0c-4f2c-4f9d-82ed-b8cb78b26064)

Note that this is Registration not signing in. Clarification required as this is an urgent matter @Mo-Naga  @ali-bahr @mostafarabie5 @Abdulrahman-Mostafa10

**Comment by ali-bahr** [comment]
the issue should be solved now please check now.
@mohamedselbohy
