### ISSUE TITLE
[API] Missing /users/profile/email

### ISSUE THREAD

**Issue by mukhaledd** [TeleGrammy/backend#52]
endpoint "/api/v1/user/profile/email" isn't found in profile-management module.
![Screenshot 2024-11-24 000019](https://github.com/user-attachments/assets/1c837695-cc02-4e86-a7a2-b570525ffaa2)

**Comment by Abdulrahman-Mostafa10** [comment]
Gonna check it

**Comment by Abdulrahman-Mostafa10** [comment]
@mukhaledd Can you please check it once again, I have just tested it and it works pretty well, could you nicely check it again and mention me back :)

**Comment by Abdulrahman-Mostafa10** [comment]
@mukhaledd  Can you please inform me with the details of your problem

**Comment by ali-bahr** [comment]
![image](https://github.com/user-attachments/assets/a60f42b9-0ada-4de0-b317-da820e7db7cf)

we are sure that it works. please make sure that your module/profile-management branch is up to date. @mukhaledd 
if you still have the same problem please provide extra information about it.
