### ISSUE TITLE
[PRODUCTION] merged code in profile-mgmt. is not up to date 

### ISSUE THREAD

**Issue by mohamedselbohy** [TeleGrammy/backend#54]
OAuth is still returning a json object instead of setting cookies and redirecting as made in registration module. Please merge the code carefully next time and test it thoroughly to make sure everything is fine.

**Comment by Abdulrahman-Mostafa10** [comment]
Khalas ba2a ya3am merged wallahy

**Comment by Abdulrahman-Mostafa10** [comment]
Khalas ba2a ya3am merged wallahy
