### ISSUE TITLE
[BUG] Verification mail is sent after sign up even if email is duplicated and signup failed

### ISSUE THREAD

**Issue by mohamedselbohy** [TeleGrammy/backend#55]
![WhatsApp Image 2024-11-25 at 19 15 37_e6eb8059](https://github.com/user-attachments/assets/17505487-02ad-4f38-b4e0-e8a6ad06b216)
![WhatsApp Image 2024-11-25 at 19 15 37_da1f87c0](https://github.com/user-attachments/assets/45b89612-1764-48ce-a973-4cce9756daa0)
Here the email form gives duplicate email. And signup fails. Then it sends verification mail, no matter what.

# ***This is an URGENT matter please fix ASAP***

![image](https://github.com/user-attachments/assets/e2072725-982b-4c3d-bfd7-def73fc56efc)

**Comment by Mo-Naga** [comment]
Fixed with the last verision on main as the issue happend due to miss merging occured before
