### ISSUE TITLE
[VULNERABILITY] Login sends hashed password back to the user.

### ISSUE THREAD

**Issue by mohamedselbohy** [TeleGrammy/backend#56]
![WhatsApp Image 2024-11-25 at 20 28 31_2790154c](https://github.com/user-attachments/assets/c9a96a86-ed33-4968-915d-2fd84d94b3ac)
![WhatsApp Image 2024-11-25 at 20 29 27_9e88bf1a](https://github.com/user-attachments/assets/6e18c70b-3de8-4608-8c53-e68059bfb881)

**Comment by Abdulrahman-Mostafa10** [comment]
I have just fixed it now, please check it

**Comment by Abdulrahman-Mostafa10** [comment]
I have just fixed it now, please check it
