### ISSUE TITLE
[BUG] Asking for password on email change through settings.

### ISSUE THREAD

**Issue by mukhaledd** [TeleGrammy/backend#61]
![Screenshot 2024-11-26 234630](https://github.com/user-attachments/assets/897c2f08-0fd1-4968-a957-52c02b29e4a4)

**Comment by Abdulrahman-Mostafa10** [comment]
@mukhaledd  I have fixed it and asked for a pull request, please check its merging status from here <a href="https://github.com/TeleGrammy/backend/pull/63">63</a>, and test it and inform us please :)

**Comment by mohamedselbohy** [comment]
PR #63 Just got merged! @mukhaledd. And it's available on the docker image as per the action https://github.com/TeleGrammy/backend/actions/runs/1205084896
