### ISSUE TITLE
Fetching contacts

### ISSUE THREAD

**Issue by Roshdy23** [TeleGrammy/backend#99]
when fetching the contacts it returns an error says "contacts are required as non empty array"  but the contacts array are already non empty array  

![WhatsApp Image 2024-12-02 at 5 45 22 PM](https://github.com/user-attachments/assets/53c93043-576f-4351-ad1c-56bc7c8761ef)
![WhatsApp Image 2024-12-02 at 5 45 22 PM](https://github.com/user-attachments/assets/81c67f36-cf93-430a-bf11-94f49b74f22b)

**Comment by Mo-Naga** [comment]
The problem solved by using axios in Frontend instead of Fetch
